---
title: "TP1_ADM"
author: "Arthur TENA"
date: "10/3/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercice 1 :question 1

```{r}
WINE=read.csv("/Users/arthurtena/Documents/wine.csv")
WINE
## centré toutes les variables :
Quan=WINE[,4:32] ## ne donne que les variables quantitatives de WINE

```

```{r}
W=diag(1/21, 21) # matrice des poids
M=diag(1/29, 29)
I_21=rep(1, 21) #matrice identité de taille 21
Quan=WINE[,4:32]
Q=matrix(0, nrow=21, ncol=29) #matrice des variables quantitatives
for(j in 1:29){ 
  Q[,j]=Quan[[j]]
}
x_b=t(Q)%*%W%*%I_21
x_c=Q - I_21%*%t(x_b) # le projecteur orthogonal sur I_21
vec_norm=diag(diag(t(x_c)%*%W%*%x_c)) #normes des vecteurs``
x_cr=x_c%*%solve(sqrt(vec_norm)) #normalisation des projetes
bar=t(x_cr)%*%W%*%I_21
barycentre=t(bar)
print(barycentre)
inertie=sum(diag(t(x_cr)%*%W%*%x_cr))
print(inertie)
```

##Exercice 1 : question 2

```{r}
WINE
Bourg=subset(WINE, WINE$Label=='Bourgueuil')
Bourg2=Bourg[,4:32]
B=matrix(0, nrow=6, ncol=29)
Chin=subset(WINE, WINE$Label=='Chinon')
Chin2=Chin[,4:32]
C=matrix(0, nrow=4, ncol=29)
Saum=subset(WINE, WINE$Label=='Saumur')
Saum2=Saum[,4:32]
S=matrix(0, nrow=11, ncol=29)

for(j in 1:29){ 
  B[,j]=Bourg2[[j]] ## je crée la matrice B avec les informations sur les bourgueui
}

for(j in 1:29){ 
  C[,j]=Chin2[[j]] ## je crée la matrice C avec les informations sur les chinon
}

for(j in 1:29){ 
  S[,j]=Saum2[[j]]  ## je crée la matrice S avec les informations sur les saumur
}

Poids_Chinon=0
Poids_Bourgueuil=0
Poids_Saumur=0
for (i in 1:21){
   if(WINE[i,2]=="Bourgueuil"){Poids_Bourgueuil = Poids_Bourgueuil+1}
  else if(WINE[i,2]=="Chinon"){Poids_Chinon = Poids_Chinon+1}
  else { Poids_Saumur = Poids_Saumur+1}
}

W_B=diag(1/Poids_Bourgueuil, Poids_Bourgueuil)
I_6=rep(1, 6)
W_C=diag(1/Poids_Chinon, Poids_Chinon)
I_4=rep(1, 4)
W_S=diag(1/Poids_Saumur, Poids_Saumur)
I_11=rep(1,11)

## calcul du barycentre de bourgueuil 
x_bg=t(B)%*%W_B%*%I_6 #dans le cours ^x vecteur avec toutes les moyennes de la classe bourgueuil 
x_bgt=t(x_bg)
x_bc=B-I_6%*%x_bgt #dans le cours x tilde ou x centré
vec_norm_b=diag(diag(t(x_bc)%*%W_B%*%x_bc))
x_bcr=x_bc%*%solve(sqrt(vec_norm_b))
bar=t(x_bc)%*%W_B%*%I_6 
barycentre_b=t(bar)
print(barycentre_b)

## calcul du barycentre de chinon 
x_cg=t(C)%*%W_C%*%I_4 #dans le cours ^x vecteur avec toutes les moyennes de la classe bourgueuil 
x_cgt=t(x_cg)
x_cc=C-I_4%*%x_cgt #dans le cours x tilde ou x centré
vec_norm_c=diag(diag(t(x_cc)%*%W_C%*%x_cc))
x_ccr=x_cc%*%solve(sqrt(vec_norm_c))
bar=t(x_ccr)%*%W_C%*%I_4 
barycentre_c=t(bar)
#print(barycentre_c)


## calcul du barycentre de Saumur  
x_sg=t(S)%*%W_S%*%I_11
x_sgt=t(x_sg)
x_sc=S-I_11%*%x_sgt
vec_norm_s=diag(diag(t(x_sc)%*%W_S%*%x_sc))
x_scr=x_sc%*%solve(sqrt(vec_norm_s))
bar=t(x_scr)%*%W_S%*%I_11 
barycentre_s=t(bar)
#print(barycentre_s)
```

```{r}
W=diag(1/21, 21) # matrice des poids
M=diag(1/29, 29)
I_21=rep(1, 21) #matrice identité de taille 21
Quan=WINE[,4:32]
Q=matrix(0, nrow=21, ncol=29) #matrice des variables quantitatives
for(j in 1:29){ 
  Q[,j]=Quan[[j]]
}
x_b=t(Q)%*%W%*%I_21
x_c=Q - I_21%*%t(x_b) # le projecteur orthogonal sur I_21
vec_norm=diag(diag(t(x_c)%*%W%*%x_c)) #normes des vecteurs``
x_cr=x_c%*%solve(sqrt(vec_norm)) #normalisation des projetes
tableau_cr=as.data.frame(x_cr)
bar=t(x_cr)%*%W%*%I_21
barycentre=t(bar)
print(barycentre)
inertie=sum(diag(t(x_cr)%*%W%*%x_cr))
print(inertie)
```

```{r}
for (i in (1:21)){
  for (j in (1:29)){
    WINE[i,j+3]=tableau_cr[i,j]
  }
}
colMeans(WINE[,4:32], na.rm = T)
inertie_total = sum(colMeans((WINE[1:21,4:32])^2, na.rm = TRUE))
inertie_total
Bourg=subset(WINE, WINE$Label=='Bourgueuil')
Bourg2=Bourg[,4:32]
B=matrix(0, nrow=6, ncol=29)
Chin=subset(WINE, WINE$Label=='Chinon')
Chin2=Chin[,4:32]
C=matrix(0, nrow=4, ncol=29)
Saum=subset(WINE, WINE$Label=='Saumur')
Saum2=Saum[,4:32]
S=matrix(0, nrow=11, ncol=29)

for(j in 1:29){ 
  B[,j]=Bourg2[[j]] ## je crée la matrice B avec les informations sur les bourgueuils
}

for(j in 1:29){ 
  C[,j]=Chin2[[j]] ## je crée la matrice C avec les informations sur les chinons
}

for(j in 1:29){ 
  S[,j]=Saum2[[j]]  ## je crée la matrice S avec les informations sur les saumurs
}

Poids_Chinon=0
Poids_Bourgueuil=0
Poids_Saumur=0
for (i in 1:21){
   if(WINE[i,2]=="Bourgueuil"){Poids_Bourgueuil = Poids_Bourgueuil+1}
  else if(WINE[i,2]=="Chinon"){Poids_Chinon = Poids_Chinon+1}
  else { Poids_Saumur = Poids_Saumur+1}
}

W_B=diag(Poids_Bourgueuil/21, Poids_Bourgueuil)
W_C=diag(Poids_Chinon/21, Poids_Chinon)
W_S=diag(Poids_Saumur/21, Poids_Saumur)
Bar_bourgueuil=colMeans(Bourg2)
Bar_Chinon=colMeans(Chin2)
Bar_Saumur=colMeans(Saum2)
Barycentre_tot=rbind(Bar_bourgueuil,Bar_Chinon,Bar_Saumur)
```

##Exercice 1 : question 2

```{r}

## Calcul de la norme carré des barycentres : 
#Bourgueuil :
norme_eu_b=sum(Bar_bourgueuil^2)

#Chinon :
norme_eu_c=sum(Bar_Chinon^2)

#Saumur :
norme_eu_s=sum(Bar_Saumur^2)

print(c(norme_eu_b,norme_eu_c,norme_eu_s))


inertie_externe = norme_eu_b*(Poids_Bourgueuil/21) + norme_eu_c*(Poids_Chinon/21) + norme_eu_s*(Poids_Saumur/21)
print(inertie_externe)
print(inertie)
R2 = inertie_externe/inertie
print(R2)
pourecentagedisparite = R2*100
print(pourecentagedisparite)
```


##Exercice 1 : question 3

```{r}
R2_variable = numeric(29)
R2_variable = (Poids_Bourgueuil/21)*Bar_bourgueuil**2 + (Poids_Chinon/21)*Bar_Chinon**2 + (Poids_Saumur/21)*Bar_Saumur**2
R2_variable

print("la moyenne arithmétique des R2 des variables:")
mean(R2_variable)
print('R2 de la partition:')
R2
```
